manager:
  private_ip: 192.168.121.137
  public_ip: 10.239.3.63

postgresql_server:
  postgres_password: 'areallystrongandsecretpasswordforpostgres'
  
  cert_path: '/home/centos/.cloudify-test-ca/10.239.3.63.crt'
  key_path: '/home/centos/.cloudify-test-ca/10.239.3.63.key'
  ca_path: '/home/centos/.cloudify-test-ca/ca.crt'
  
  cluster:
    nodes:
      cfy5.1-1.openstacklocal:
        ip: 10.239.3.63
      cfy5.1-2.openstacklocal:
        ip: 10.239.3.64
      cfy5.1-3.openstacklocal:
        ip: 10.239.3.65

    etcd:
      cluster_token: 'astrongandsecretpasswordlikestring'
      root_password: 'anotherstrongandsecretbutdifferentpassword'
      patroni_password: 'yetanotherstrongandsecretpassword'

    patroni:
      rest_user: patroni
      rest_password: 'strongandsecretpatronirestpassword'

    postgres:
      replicator_password: 'stillanotherstrongandsecretpassword'

prometheus:
  credentials:
    username: 'monitoringusername'
    password: 'longyeteasytorememberstringasapassword'

  cert_path: '/home/centos/.cloudify-test-ca/10.239.3.63.crt'
  key_path: '/home/centos/.cloudify-test-ca/10.239.3.63.key'
  ca_path: '/home/centos/.cloudify-test-ca/ca.crt'

services_to_install:
  - database_service
  - monitoring_service

